import = ["~/.config/alacritty/theme.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = 'xterm-256color'

[window]
padding = { x = 8, y = 8 }

[font]
size = 11
normal = { family = "VictorMono Nerd Font", style = "regular" }
bold = { family = "VictorMono Nerd Font", style = "bold" }
italic = { family = "VictorMono Nerd Font", style = "medium italic" }
bold_italic = { family = "VictorMono Nerd Font", style = "bold italic" }
builtin_box_drawing = true

[cursor]
style = { shape = "Underline", blinking = "Always" }
