add_newline = false

format = """$os\
$username\
$hostname\
$directory\
$package\
$cmd_duration\
$character\
"""

[character]
error_symbol = "[►](bold red)"
success_symbol = "[►](bold #687387)"

[os]
disabled = false
format = '[$symbol]($style bold)'
style = "fg:#2b96fb"

[os.symbols]
Arch = "󱐋 "

[fill]
style = 'bold yellow'
symbol = '.'

[username]
disabled = false
format = '[$user ]($style)'
show_always = true
style_user = 'fg:#687387'

[directory]
format = "[at ]($style)[$path]($style)[$read_only]($read_only_style) "
home_symbol = "~"
read_only = "  "
read_only_style = "197"
truncation_length = 1
truncation_symbol = "…/"
style = "fg:#687387"

[hostname]
style = "bold purple"

[kubernetes]
style = "bold blue"

# [git_branch]
# format = "[on](#687387) [$branch]($style) "
# style = "#25e8b4"
#
# [git_status]
# ahead = '⇡${count}(#3fcca2) '
# behind = '⇣${count}(#cc3f62) '
# conflicted = '󰘕 (#fa3e5b) '
# deleted = '󰺝 (#fa3e5b)'
# diverged = '⇕⇡${ahead_count}⇣${behind_count} '
# modified = ' (#61b6f2)'
# renamed = '󰚼 '
# staged = '[++\($count\)](green) '
# stashed = '󰏗 '
# untracked = ' '
# up_to_date = ' '
#
# [git_commit]
# commit_hash_length = 4
# tag_symbol = ' '

[nodejs]
disabled = false
style = "bright-green"
symbol = "󰎙 "

[package]
format = 'via [󰏓 $version](208 bold) '

# ~/.config/starship.toml

[time]
disabled = false
format = ' [$time]($style) '
style = "cyan"
time_format = '%r'
use_12hr = true
# time_range = '10:00:00-14:00:00'
# utc_time_offset = '-5'

# ~/.config/starship.toml

[cmd_duration]
format = 'took [$duration](bold yellow)'
min_time = 500
